highlighter: 'pygments'

destination: /usr/share/nginx/www


collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
